/** Generated by itemis CREATE code generator. */

#ifndef FSM_QUALITYGATE_H_
#define FSM_QUALITYGATE_H_

/*!
Forward declaration for the FSM_QualityGate state machine.
*/
class FSM_QualityGate;


#include <deque>
#include "../src/sc_types.h"
#include "../src/sc_rxcpp.h"
#include "../src/sc_statemachine.h"
#include "../src/sc_eventdriven.h"
#include <string.h>

/*! \file
Header of the state machine 'FSM_QualityGate'.
*/


class FSM_QualityGate : public sc::EventDrivenInterface
{
	public:
		FSM_QualityGate() noexcept;
		
		virtual ~FSM_QualityGate();
		
		
		
		/*! Enumeration of all states. */
		enum class State
		{
			NO_STATE,
			FSM_QualityGate_Ingress_Ingress,
			FSM_QualityGate_Ingress_Ingress_Ingress_Idle,
			FSM_QualityGate_Ingress_Ingress_Ingress_PukPresent,
			FSM_QualityGate_Ingress_Ingress_Ingress_CreatingDistance,
			FSM_QualityGate_Ingress_Paused,
			FSM_QualityGate__HeightMeasurement_HeightMeasurement,
			FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Idle,
			FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Measuring,
			FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_PukPresent,
			FSM_QualityGate__HeightMeasurement_Paused,
			FSM_QualityGate__Sorting_Sorting,
			FSM_QualityGate__Sorting_Sorting_Sorting_Idle,
			FSM_QualityGate__Sorting_Sorting_Sorting_PukPresent,
			FSM_QualityGate__Sorting_Sorting_Sorting_passthrough,
			FSM_QualityGate__Sorting_Sorting_Sorting_ejecting,
			FSM_QualityGate__Sorting_RampFull,
			FSM_QualityGate__Sorting_Paused,
			FSM_QualityGate__Egress_Egress,
			FSM_QualityGate__Egress_Egress_Egress_IDLE,
			FSM_QualityGate__Egress_Egress_Egress_PukPresent,
			FSM_QualityGate__Egress_Egress_Egress_Transfer,
			FSM_QualityGate__Egress_Paused,
			FSM_QualityGate__Motor_SystemMotor,
			FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Idle,
			FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Forward,
			FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Slow,
			FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Stop,
			FSM_System_Operational,
			FSM_System_EStop,
			FSM_System_EStop_EStop_AwaitingEStopButton,
			FSM_System_EStop_EStop__final_,
			FSM_System_Start,
			FSM_System_Ready,
			FSM_System_ServiceMode,
			FSM_Signaling_FSM_LAMP,
			FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp,
			FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Off,
			FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Constant,
			FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Blinking_1Hz,
			FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Off,
			FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Constant,
			FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Blinking_1Hz,
			FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Off,
			FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Constant
		};
		
		/*! The number of states. */
		static constexpr const sc::integer numStates {44};
		static constexpr const sc::integer scvi_FSM_QualityGate_Ingress_Ingress {0};
		static constexpr const sc::integer scvi_FSM_QualityGate_Ingress_Ingress_Ingress_Idle {0};
		static constexpr const sc::integer scvi_FSM_QualityGate_Ingress_Ingress_Ingress_PukPresent {0};
		static constexpr const sc::integer scvi_FSM_QualityGate_Ingress_Ingress_Ingress_CreatingDistance {0};
		static constexpr const sc::integer scvi_FSM_QualityGate_Ingress_Paused {0};
		static constexpr const sc::integer scvi_FSM_QualityGate__HeightMeasurement_HeightMeasurement {1};
		static constexpr const sc::integer scvi_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Idle {1};
		static constexpr const sc::integer scvi_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Measuring {1};
		static constexpr const sc::integer scvi_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_PukPresent {1};
		static constexpr const sc::integer scvi_FSM_QualityGate__HeightMeasurement_Paused {1};
		static constexpr const sc::integer scvi_FSM_QualityGate__Sorting_Sorting {2};
		static constexpr const sc::integer scvi_FSM_QualityGate__Sorting_Sorting_Sorting_Idle {2};
		static constexpr const sc::integer scvi_FSM_QualityGate__Sorting_Sorting_Sorting_PukPresent {2};
		static constexpr const sc::integer scvi_FSM_QualityGate__Sorting_Sorting_Sorting_passthrough {2};
		static constexpr const sc::integer scvi_FSM_QualityGate__Sorting_Sorting_Sorting_ejecting {2};
		static constexpr const sc::integer scvi_FSM_QualityGate__Sorting_RampFull {2};
		static constexpr const sc::integer scvi_FSM_QualityGate__Sorting_Paused {2};
		static constexpr const sc::integer scvi_FSM_QualityGate__Egress_Egress {3};
		static constexpr const sc::integer scvi_FSM_QualityGate__Egress_Egress_Egress_IDLE {3};
		static constexpr const sc::integer scvi_FSM_QualityGate__Egress_Egress_Egress_PukPresent {3};
		static constexpr const sc::integer scvi_FSM_QualityGate__Egress_Egress_Egress_Transfer {3};
		static constexpr const sc::integer scvi_FSM_QualityGate__Egress_Paused {3};
		static constexpr const sc::integer scvi_FSM_QualityGate__Motor_SystemMotor {4};
		static constexpr const sc::integer scvi_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Idle {4};
		static constexpr const sc::integer scvi_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Forward {4};
		static constexpr const sc::integer scvi_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Slow {4};
		static constexpr const sc::integer scvi_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Stop {4};
		static constexpr const sc::integer scvi_FSM_System_Operational {5};
		static constexpr const sc::integer scvi_FSM_System_EStop {5};
		static constexpr const sc::integer scvi_FSM_System_EStop_EStop_AwaitingEStopButton {5};
		static constexpr const sc::integer scvi_FSM_System_EStop_EStop__final_ {5};
		static constexpr const sc::integer scvi_FSM_System_Start {5};
		static constexpr const sc::integer scvi_FSM_System_Ready {5};
		static constexpr const sc::integer scvi_FSM_System_ServiceMode {5};
		static constexpr const sc::integer scvi_FSM_Signaling_FSM_LAMP {6};
		static constexpr const sc::integer scvi_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp {6};
		static constexpr const sc::integer scvi_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Off {6};
		static constexpr const sc::integer scvi_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Constant {6};
		static constexpr const sc::integer scvi_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Blinking_1Hz {6};
		static constexpr const sc::integer scvi_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Off {7};
		static constexpr const sc::integer scvi_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Constant {7};
		static constexpr const sc::integer scvi_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Blinking_1Hz {7};
		static constexpr const sc::integer scvi_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Off {8};
		static constexpr const sc::integer scvi_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Constant {8};
		
		/*! Enumeration of all events which are consumed. */
		enum class Event
		{
			NO_EVENT,
			ESTOP_1_HIGH,
			ESTOP_1_LOW,
			LBF_1_INTERRUPTED,
			LBF_1_OPEN,
			PUK_ENTRY_HeightMeasurement,
			INGRESS_IN,
			INGRESS_OUT,
			HS_1_SAMPLE,
			HS_1_SAMPLING_DONE,
			PUK_ENTRY_SORTING,
			TIMEOUT_200,
			LBM_1_INTERRUPTED,
			LBM_1_OPEN,
			MS_TRUE,
			MS_FALSE,
			PUK_DESIRED,
			PUK_NOT_DESIRED,
			PUK_EJECTOR_DISTANCE_VALID,
			LBR_1_INTERRUPTED,
			LBR_1_OPEN,
			LBE_1_OPEN,
			LBE_1_INTERRUPTED,
			BGS_1_LONG_PRESSED,
			BGS_1_INTERRUPTED,
			BRS_1_INTERRUPTED,
			BGR_1_INTERRUPTED,
			LampEStop,
			Lamp,
			ESTOP_SIGNAL,
			ESTOP_SIGNAL_RESET,
			RUNNING_SIGNAL,
			RUNNING_SIGNAL_RESET,
			WARNING_SIGNAL,
			WARNING_SIGNAL_RESET,
			READY_SIGNAL,
			READY_RESET,
			ERROR_SIGNAL,
			Internal_local_SYSTEM_OPERATIONAL_OUT,
			Internal_local_PUK_DISTANCE_VALID,
			Internal_local_SYSTEM_OPERATIONAL_IN,
			Internal_local_PUK_ENTRY_EGRESS,
			Internal_local_ESTOP_RECEIVED,
			Internal_local_SYSTEM_SERVICE_IN,
			Internal_local_ESTOP_CLEARED,
			Internal_local_SYSTEM_SERVICE_OUT
		};
		
		class EventInstance
		{
			public:
				explicit  EventInstance(Event id) noexcept : eventId(id){}
				virtual ~EventInstance() = default;
				const Event eventId;
		};
		/*! Get observable for event 'SYSTEM_OPERATIONAL_IN' of default interface scope. */
		sc::rx::Observable<void>& getSYSTEM_OPERATIONAL_IN() noexcept;
		/*! Get observable for event 'SYSTEM_OPERATIONAL_OUT' of default interface scope. */
		sc::rx::Observable<void>& getSYSTEM_OPERATIONAL_OUT() noexcept;
		/*! Get observable for event 'SYSTEM_SERVICE_IN' of default interface scope. */
		sc::rx::Observable<void>& getSYSTEM_SERVICE_IN() noexcept;
		/*! Get observable for event 'SYSTEM_SERVICE_OUT' of default interface scope. */
		sc::rx::Observable<void>& getSYSTEM_SERVICE_OUT() noexcept;
		/*! Raises the in event 'ESTOP_1_HIGH' of default interface scope. */
		void raiseESTOP_1_HIGH();
		/*! Raises the in event 'ESTOP_1_LOW' of default interface scope. */
		void raiseESTOP_1_LOW();
		/*! Get observable for event 'ESTOP_RECEIVED' of default interface scope. */
		sc::rx::Observable<void>& getESTOP_RECEIVED() noexcept;
		/*! Get observable for event 'ESTOP_CLEARED' of default interface scope. */
		sc::rx::Observable<void>& getESTOP_CLEARED() noexcept;
		/*! Raises the in event 'LBF_1_INTERRUPTED' of default interface scope. */
		void raiseLBF_1_INTERRUPTED();
		/*! Raises the in event 'LBF_1_OPEN' of default interface scope. */
		void raiseLBF_1_OPEN();
		/*! Raises the in event 'PUK_ENTRY_HeightMeasurement' of default interface scope. */
		void raisePUK_ENTRY_HeightMeasurement();
		/*! Raises the in event 'INGRESS_IN' of default interface scope. */
		void raiseINGRESS_IN();
		/*! Raises the in event 'INGRESS_OUT' of default interface scope. */
		void raiseINGRESS_OUT();
		/*! Raises the in event 'HS_1_SAMPLE' of default interface scope. */
		void raiseHS_1_SAMPLE();
		/*! Raises the in event 'HS_1_SAMPLING_DONE' of default interface scope. */
		void raiseHS_1_SAMPLING_DONE();
		/*! Get observable for event 'PUK_DISTANCE_VALID' of default interface scope. */
		sc::rx::Observable<void>& getPUK_DISTANCE_VALID() noexcept;
		/*! Raises the in event 'PUK_ENTRY_SORTING' of default interface scope. */
		void raisePUK_ENTRY_SORTING();
		/*! Raises the in event 'TIMEOUT_200' of default interface scope. */
		void raiseTIMEOUT_200();
		/*! Raises the in event 'LBM_1_INTERRUPTED' of default interface scope. */
		void raiseLBM_1_INTERRUPTED();
		/*! Raises the in event 'LBM_1_OPEN' of default interface scope. */
		void raiseLBM_1_OPEN();
		/*! Raises the in event 'MS_TRUE' of default interface scope. */
		void raiseMS_TRUE();
		/*! Raises the in event 'MS_FALSE' of default interface scope. */
		void raiseMS_FALSE();
		/*! Raises the in event 'PUK_DESIRED' of default interface scope. */
		void raisePUK_DESIRED();
		/*! Raises the in event 'PUK_NOT_DESIRED' of default interface scope. */
		void raisePUK_NOT_DESIRED();
		/*! Get observable for event 'PUK_ENTRY_EGRESS' of default interface scope. */
		sc::rx::Observable<void>& getPUK_ENTRY_EGRESS() noexcept;
		/*! Raises the in event 'PUK_EJECTOR_DISTANCE_VALID' of default interface scope. */
		void raisePUK_EJECTOR_DISTANCE_VALID();
		/*! Raises the in event 'LBR_1_INTERRUPTED' of default interface scope. */
		void raiseLBR_1_INTERRUPTED();
		/*! Raises the in event 'LBR_1_OPEN' of default interface scope. */
		void raiseLBR_1_OPEN();
		/*! Get observable for event 'SORTING_MODULE_ACTIVE' of default interface scope. */
		sc::rx::Observable<void>& getSORTING_MODULE_ACTIVE() noexcept;
		/*! Get observable for event 'SORTING_MODULE_RESTING' of default interface scope. */
		sc::rx::Observable<void>& getSORTING_MODULE_RESTING() noexcept;
		/*! Raises the in event 'LBE_1_OPEN' of default interface scope. */
		void raiseLBE_1_OPEN();
		/*! Raises the in event 'LBE_1_INTERRUPTED' of default interface scope. */
		void raiseLBE_1_INTERRUPTED();
		/*! Get observable for event 'MOTOR_STOP' of default interface scope. */
		sc::rx::Observable<void>& getMOTOR_STOP() noexcept;
		/*! Get observable for event 'MOTOR_FAST' of default interface scope. */
		sc::rx::Observable<void>& getMOTOR_FAST() noexcept;
		/*! Get observable for event 'MOTOR_SLOW' of default interface scope. */
		sc::rx::Observable<void>& getMOTOR_SLOW() noexcept;
		/*! Raises the in event 'BGS_1_LONG_PRESSED' of default interface scope. */
		void raiseBGS_1_LONG_PRESSED();
		/*! Raises the in event 'BGS_1_INTERRUPTED' of default interface scope. */
		void raiseBGS_1_INTERRUPTED();
		/*! Raises the in event 'BRS_1_INTERRUPTED' of default interface scope. */
		void raiseBRS_1_INTERRUPTED();
		/*! Raises the in event 'BGR_1_INTERRUPTED' of default interface scope. */
		void raiseBGR_1_INTERRUPTED();
		/*! Raises the in event 'LampEStop' of default interface scope. */
		void raiseLampEStop();
		/*! Raises the in event 'Lamp' of default interface scope. */
		void raiseLamp();
		/*! Get observable for event 'LG1_ON' of default interface scope. */
		sc::rx::Observable<void>& getLG1_ON() noexcept;
		/*! Get observable for event 'LG1_BLINKING_1HZ' of default interface scope. */
		sc::rx::Observable<void>& getLG1_BLINKING_1HZ() noexcept;
		/*! Get observable for event 'LG1_OFF' of default interface scope. */
		sc::rx::Observable<void>& getLG1_OFF() noexcept;
		/*! Get observable for event 'LY1_ON' of default interface scope. */
		sc::rx::Observable<void>& getLY1_ON() noexcept;
		/*! Get observable for event 'LY1_BLINKING_1HZ' of default interface scope. */
		sc::rx::Observable<void>& getLY1_BLINKING_1HZ() noexcept;
		/*! Get observable for event 'LY1_OFF' of default interface scope. */
		sc::rx::Observable<void>& getLY1_OFF() noexcept;
		/*! Get observable for event 'LR1_ON' of default interface scope. */
		sc::rx::Observable<void>& getLR1_ON() noexcept;
		/*! Get observable for event 'LR1_OFF' of default interface scope. */
		sc::rx::Observable<void>& getLR1_OFF() noexcept;
		/*! Get observable for event 'SYSTEM_RUNNING' of default interface scope. */
		sc::rx::Observable<void>& getSYSTEM_RUNNING() noexcept;
		/*! Get observable for event 'SYSTEM_STOPPED' of default interface scope. */
		sc::rx::Observable<void>& getSYSTEM_STOPPED() noexcept;
		/*! Raises the in event 'ESTOP_SIGNAL' of default interface scope. */
		void raiseESTOP_SIGNAL();
		/*! Raises the in event 'ESTOP_SIGNAL_RESET' of default interface scope. */
		void raiseESTOP_SIGNAL_RESET();
		/*! Raises the in event 'RUNNING_SIGNAL' of default interface scope. */
		void raiseRUNNING_SIGNAL();
		/*! Raises the in event 'RUNNING_SIGNAL_RESET' of default interface scope. */
		void raiseRUNNING_SIGNAL_RESET();
		/*! Raises the in event 'WARNING_SIGNAL' of default interface scope. */
		void raiseWARNING_SIGNAL();
		/*! Raises the in event 'WARNING_SIGNAL_RESET' of default interface scope. */
		void raiseWARNING_SIGNAL_RESET();
		/*! Raises the in event 'READY_SIGNAL' of default interface scope. */
		void raiseREADY_SIGNAL();
		/*! Raises the in event 'READY_RESET' of default interface scope. */
		void raiseREADY_RESET();
		/*! Raises the in event 'ERROR_SIGNAL' of default interface scope. */
		void raiseERROR_SIGNAL();
		
		
		/*! Gets the value of the variable 'calibrated' that is defined in the default interface scope. */
		bool getCalibrated() const noexcept;
		/*! Sets the value of the variable 'calibrated' that is defined in the default interface scope. */
		void setCalibrated(bool calibrated) noexcept;
		/*! Gets the value of the variable 'eStopActive' that is defined in the default interface scope. */
		bool getEStopActive() const noexcept;
		/*! Sets the value of the variable 'eStopActive' that is defined in the default interface scope. */
		void setEStopActive(bool eStopActive) noexcept;
		/*! Gets the value of the variable 'FST1RampFull' that is defined in the default interface scope. */
		bool getFST1RampFull() const noexcept;
		/*! Sets the value of the variable 'FST1RampFull' that is defined in the default interface scope. */
		void setFST1RampFull(bool FST1RampFull) noexcept;
		/*! Gets the value of the variable 'timePassed' that is defined in the default interface scope. */
		sc::integer getTimePassed() const noexcept;
		/*! Sets the value of the variable 'timePassed' that is defined in the default interface scope. */
		void setTimePassed(sc::integer timePassed) noexcept;
		/*! Gets the value of the variable 'ramp1Full' that is defined in the default interface scope. */
		bool getRamp1Full() const noexcept;
		/*! Sets the value of the variable 'ramp1Full' that is defined in the default interface scope. */
		void setRamp1Full(bool ramp1Full) noexcept;
		/*! Gets the value of the variable 'metalDetected' that is defined in the default interface scope. */
		bool getMetalDetected() const noexcept;
		/*! Sets the value of the variable 'metalDetected' that is defined in the default interface scope. */
		void setMetalDetected(bool metalDetected) noexcept;
		/*! Gets the value of the variable 'motorStop' that is defined in the default interface scope. */
		sc::integer getMotorStop() const noexcept;
		/*! Sets the value of the variable 'motorStop' that is defined in the default interface scope. */
		void setMotorStop(sc::integer motorStop) noexcept;
		/*! Gets the value of the variable 'motorSlow' that is defined in the default interface scope. */
		sc::integer getMotorSlow() const noexcept;
		/*! Sets the value of the variable 'motorSlow' that is defined in the default interface scope. */
		void setMotorSlow(sc::integer motorSlow) noexcept;
		/*! Gets the value of the variable 'motorForward' that is defined in the default interface scope. */
		sc::integer getMotorForward() const noexcept;
		/*! Sets the value of the variable 'motorForward' that is defined in the default interface scope. */
		void setMotorForward(sc::integer motorForward) noexcept;
		/*! Gets the value of the variable 'eStop_lamp_active' that is defined in the default interface scope. */
		bool getEStop_lamp_active() const noexcept;
		/*! Sets the value of the variable 'eStop_lamp_active' that is defined in the default interface scope. */
		void setEStop_lamp_active(bool eStop_lamp_active) noexcept;
		/*! Gets the value of the variable 'running_lamp_active' that is defined in the default interface scope. */
		bool getRunning_lamp_active() const noexcept;
		/*! Sets the value of the variable 'running_lamp_active' that is defined in the default interface scope. */
		void setRunning_lamp_active(bool running_lamp_active) noexcept;
		/*! Gets the value of the variable 'warning_lamp_active' that is defined in the default interface scope. */
		bool getWarning_lamp_active() const noexcept;
		/*! Sets the value of the variable 'warning_lamp_active' that is defined in the default interface scope. */
		void setWarning_lamp_active(bool warning_lamp_active) noexcept;
		
		/*! Can be used by the client code to trigger a run to completion step without raising an event. */
		void triggerWithoutEvent() override;
		
		/*
		 * Functions inherited from StatemachineInterface
		 */
		 void enter() override;
		
		 void exit() override;
		
		/*!
		 * Checks if the state machine is active (until 2.4.1 this method was used for states).
		 * A state machine is active if it has been entered. It is inactive if it has not been entered at all or if it has been exited.
		 */
		 bool isActive() const noexcept override;
		
		
		/*!
		* Checks if all active states are final. 
		* If there are no active states then the state machine is considered being inactive. In this case this method returns false.
		*/
		 bool isFinal() const noexcept override;
		
		/*! 
		 * Checks if member of the state machine must be set. For example an operation callback.
		 */
		bool check() const noexcept;
		
		
		/*! Checks if the specified state is active (until 2.4.1 the used method for states was calles isActive()). */
		bool isStateActive(State state) const noexcept;
		
		
		
	protected:
		
		
		std::deque<EventInstance*> incomingEventQueue;
		
		std::deque<EventInstance*> internalEventQueue;
		
		EventInstance* getNextEvent() noexcept;
		
		bool dispatchEvent(EventInstance* event) noexcept;
		
		
		
	private:
		
		bool calibrated {false};
		bool eStopActive {false};
		bool FST1RampFull {false};
		sc::integer timePassed {0};
		bool ramp1Full {false};
		bool metalDetected {false};
		sc::integer motorStop {0};
		sc::integer motorSlow {0};
		sc::integer motorForward {0};
		bool eStop_lamp_active {false};
		bool running_lamp_active {false};
		bool warning_lamp_active {false};
		
		
		
		
		
		//! the maximum number of orthogonal states defines the dimension of the state configuration vector.
		static const sc::ushort maxOrthogonalStates {9};
		//! dimension of the state configuration vector for history states
		static const sc::ushort maxHistoryStates {1};
		
		
		
		State stateConfVector[maxOrthogonalStates];
		
		State historyVector[maxHistoryStates];
		
		
		
		bool isExecuting {false};
		sc::integer stateConfVectorPosition {0};
		
		
		
		// prototypes of all internal functions
		
		void enact_FSM_QualityGate_Ingress_Ingress_Ingress_Idle();
		void enact_FSM_QualityGate_Ingress_Ingress_Ingress_PukPresent();
		void enact_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Measuring();
		void enact_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_PukPresent();
		void enact_FSM_QualityGate__Sorting_RampFull();
		void enact_FSM_QualityGate__Egress_Egress_Egress_Transfer();
		void enact_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Idle();
		void enact_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Forward();
		void enact_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Slow();
		void enact_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Stop();
		void enact_FSM_System_Operational();
		void enact_FSM_System_EStop();
		void enact_FSM_System_ServiceMode();
		void enact_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Off();
		void enact_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Constant();
		void enact_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Blinking_1Hz();
		void enact_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Off();
		void enact_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Constant();
		void enact_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Blinking_1Hz();
		void enact_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Off();
		void enact_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Constant();
		void exact_FSM_QualityGate_Ingress_Ingress_Ingress_Idle();
		void exact_FSM_QualityGate_Ingress_Ingress_Ingress_CreatingDistance();
		void exact_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Measuring();
		void exact_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_PukPresent();
		void exact_FSM_QualityGate__Sorting_RampFull();
		void exact_FSM_QualityGate__Egress_Egress_Egress_Transfer();
		void exact_FSM_System_Operational();
		void exact_FSM_System_EStop();
		void exact_FSM_System_ServiceMode();
		void enseq_FSM_QualityGate_Ingress_Ingress_default();
		void enseq_FSM_QualityGate_Ingress_Ingress_Ingress_Idle_default();
		void enseq_FSM_QualityGate_Ingress_Ingress_Ingress_PukPresent_default();
		void enseq_FSM_QualityGate_Ingress_Ingress_Ingress_CreatingDistance_default();
		void enseq_FSM_QualityGate_Ingress_Paused_default();
		void enseq_FSM_QualityGate__HeightMeasurement_HeightMeasurement_default();
		void enseq_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Idle_default();
		void enseq_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Measuring_default();
		void enseq_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_PukPresent_default();
		void enseq_FSM_QualityGate__HeightMeasurement_Paused_default();
		void enseq_FSM_QualityGate__Sorting_Sorting_Sorting_Idle_default();
		void enseq_FSM_QualityGate__Sorting_Sorting_Sorting_PukPresent_default();
		void enseq_FSM_QualityGate__Sorting_Sorting_Sorting_passthrough_default();
		void enseq_FSM_QualityGate__Sorting_Sorting_Sorting_ejecting_default();
		void enseq_FSM_QualityGate__Sorting_RampFull_default();
		void enseq_FSM_QualityGate__Sorting_Paused_default();
		void enseq_FSM_QualityGate__Egress_Egress_default();
		void enseq_FSM_QualityGate__Egress_Egress_Egress_IDLE_default();
		void enseq_FSM_QualityGate__Egress_Egress_Egress_PukPresent_default();
		void enseq_FSM_QualityGate__Egress_Egress_Egress_Transfer_default();
		void enseq_FSM_QualityGate__Egress_Paused_default();
		void enseq_FSM_QualityGate__Motor_SystemMotor_default();
		void enseq_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Idle_default();
		void enseq_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Forward_default();
		void enseq_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Slow_default();
		void enseq_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Stop_default();
		void enseq_FSM_System_Operational_default();
		void enseq_FSM_System_EStop_default();
		void enseq_FSM_System_EStop_EStop_AwaitingEStopButton_default();
		void enseq_FSM_System_EStop_EStop__final__default();
		void enseq_FSM_System_Start_default();
		void enseq_FSM_System_Ready_default();
		void enseq_FSM_System_ServiceMode_default();
		void enseq_FSM_Signaling_FSM_LAMP_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Off_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Constant_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Blinking_1Hz_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Off_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Constant_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Blinking_1Hz_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Off_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Constant_default();
		void enseq_FSM_QualityGate_Ingress_default();
		void enseq_FSM_QualityGate_Ingress_Ingress_Ingress_default();
		void enseq_FSM_QualityGate__HeightMeasurement_default();
		void enseq_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_default();
		void enseq_FSM_QualityGate__Sorting_default();
		void shenseq_FSM_QualityGate__Sorting_Sorting_Sorting();
		void enseq_FSM_QualityGate__Egress_default();
		void enseq_FSM_QualityGate__Egress_Egress_Egress_default();
		void enseq_FSM_QualityGate__Motor_default();
		void enseq_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_default();
		void enseq_FSM_System_default();
		void enseq_FSM_System_EStop_EStop_default();
		void enseq_FSM_Signaling_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_default();
		void enseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_default();
		void exseq_FSM_QualityGate_Ingress_Ingress();
		void exseq_FSM_QualityGate_Ingress_Ingress_Ingress_Idle();
		void exseq_FSM_QualityGate_Ingress_Ingress_Ingress_PukPresent();
		void exseq_FSM_QualityGate_Ingress_Ingress_Ingress_CreatingDistance();
		void exseq_FSM_QualityGate_Ingress_Paused();
		void exseq_FSM_QualityGate__HeightMeasurement_HeightMeasurement();
		void exseq_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Idle();
		void exseq_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Measuring();
		void exseq_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_PukPresent();
		void exseq_FSM_QualityGate__HeightMeasurement_Paused();
		void exseq_FSM_QualityGate__Sorting_Sorting();
		void exseq_FSM_QualityGate__Sorting_Sorting_Sorting_Idle();
		void exseq_FSM_QualityGate__Sorting_Sorting_Sorting_PukPresent();
		void exseq_FSM_QualityGate__Sorting_Sorting_Sorting_passthrough();
		void exseq_FSM_QualityGate__Sorting_Sorting_Sorting_ejecting();
		void exseq_FSM_QualityGate__Sorting_RampFull();
		void exseq_FSM_QualityGate__Sorting_Paused();
		void exseq_FSM_QualityGate__Egress_Egress();
		void exseq_FSM_QualityGate__Egress_Egress_Egress_IDLE();
		void exseq_FSM_QualityGate__Egress_Egress_Egress_PukPresent();
		void exseq_FSM_QualityGate__Egress_Egress_Egress_Transfer();
		void exseq_FSM_QualityGate__Egress_Paused();
		void exseq_FSM_QualityGate__Motor_SystemMotor();
		void exseq_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Idle();
		void exseq_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Forward();
		void exseq_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Slow();
		void exseq_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Stop();
		void exseq_FSM_System_Operational();
		void exseq_FSM_System_EStop();
		void exseq_FSM_System_EStop_EStop_AwaitingEStopButton();
		void exseq_FSM_System_EStop_EStop__final_();
		void exseq_FSM_System_Start();
		void exseq_FSM_System_Ready();
		void exseq_FSM_System_ServiceMode();
		void exseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Off();
		void exseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Constant();
		void exseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Blinking_1Hz();
		void exseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Off();
		void exseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Constant();
		void exseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Blinking_1Hz();
		void exseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Off();
		void exseq_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Constant();
		void exseq_FSM_QualityGate_Ingress();
		void exseq_FSM_QualityGate_Ingress_Ingress_Ingress();
		void exseq_FSM_QualityGate__HeightMeasurement();
		void exseq_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement();
		void exseq_FSM_QualityGate__Sorting();
		void exseq_FSM_QualityGate__Sorting_Sorting_Sorting();
		void exseq_FSM_QualityGate__Egress();
		void exseq_FSM_QualityGate__Egress_Egress_Egress();
		void exseq_FSM_QualityGate__Motor();
		void exseq_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor();
		void exseq_FSM_System();
		void exseq_FSM_System_EStop_EStop();
		void exseq_FSM_Signaling();
		void react_FSM_QualityGate_Ingress_Ingress_Ingress__entry_Default();
		void react_FSM_QualityGate_Ingress__entry_Default();
		void react_FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement__entry_Default();
		void react_FSM_QualityGate__HeightMeasurement__entry_Default();
		void react_FSM_QualityGate__Sorting_Sorting_Sorting__entry_Default();
		void react_FSM_QualityGate__Sorting__entry_Default();
		void react_FSM_QualityGate__Egress_Egress_Egress__entry_Default();
		void react_FSM_QualityGate__Egress__entry_Default();
		void react_FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor__entry_Default();
		void react_FSM_QualityGate__Motor__entry_Default();
		void react_FSM_System_EStop_EStop__entry_Default();
		void react_FSM_System__entry_Default();
		void react_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green__entry_Default();
		void react_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow__entry_Default();
		void react_FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red__entry_Default();
		void react_FSM_Signaling_FSM_LAMP_FSM_LAMP__entry_Default();
		void react_FSM_Signaling__entry_Default();
		sc::integer react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate_Ingress_Ingress_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate_Ingress_Ingress_Ingress_Idle_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate_Ingress_Ingress_Ingress_PukPresent_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate_Ingress_Ingress_Ingress_CreatingDistance_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate_Ingress_Paused_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__HeightMeasurement_HeightMeasurement_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Idle_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_Measuring_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__HeightMeasurement_HeightMeasurement_HeightMeasurement_PukPresent_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__HeightMeasurement_Paused_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Sorting_Sorting_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Sorting_Sorting_Sorting_Idle_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Sorting_Sorting_Sorting_PukPresent_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Sorting_Sorting_Sorting_passthrough_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Sorting_Sorting_Sorting_ejecting_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Sorting_RampFull_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Sorting_Paused_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Egress_Egress_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Egress_Egress_Egress_IDLE_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Egress_Egress_Egress_PukPresent_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Egress_Egress_Egress_Transfer_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Egress_Paused_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Motor_SystemMotor_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Idle_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Forward_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Slow_react(const sc::integer transitioned_before);
		sc::integer FSM_QualityGate__Motor_SystemMotor_FSM_SystemMotor_Stop_react(const sc::integer transitioned_before);
		sc::integer FSM_System_Operational_react(const sc::integer transitioned_before);
		sc::integer FSM_System_EStop_react(const sc::integer transitioned_before);
		sc::integer FSM_System_EStop_EStop_AwaitingEStopButton_react(const sc::integer transitioned_before);
		sc::integer FSM_System_EStop_EStop__final__react(const sc::integer transitioned_before);
		sc::integer FSM_System_Start_react(const sc::integer transitioned_before);
		sc::integer FSM_System_Ready_react(const sc::integer transitioned_before);
		sc::integer FSM_System_ServiceMode_react(const sc::integer transitioned_before);
		sc::integer FSM_Signaling_FSM_LAMP_react(const sc::integer transitioned_before);
		sc::integer FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_react(const sc::integer transitioned_before);
		sc::integer FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Off_react(const sc::integer transitioned_before);
		sc::integer FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Constant_react(const sc::integer transitioned_before);
		sc::integer FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Green_Blinking_1Hz_react(const sc::integer transitioned_before);
		sc::integer FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Off_react(const sc::integer transitioned_before);
		sc::integer FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Constant_react(const sc::integer transitioned_before);
		sc::integer FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Yellow_Blinking_1Hz_react(const sc::integer transitioned_before);
		sc::integer FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Off_react(const sc::integer transitioned_before);
		sc::integer FSM_Signaling_FSM_LAMP_FSM_LAMP_FSM_Lamp_FSM_Lamp_Red_Constant_react(const sc::integer transitioned_before);
		void clearInEvents() noexcept;
		void clearInternalEvents() noexcept;
		void microStep();
		void runCycle();
		
		
		
		/*! Observable for event 'SYSTEM_OPERATIONAL_IN' of default interface scope. */
		sc::rx::Observable<void> SYSTEM_OPERATIONAL_IN_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'SYSTEM_OPERATIONAL_OUT' of default interface scope. */
		sc::rx::Observable<void> SYSTEM_OPERATIONAL_OUT_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'SYSTEM_SERVICE_IN' of default interface scope. */
		sc::rx::Observable<void> SYSTEM_SERVICE_IN_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'SYSTEM_SERVICE_OUT' of default interface scope. */
		sc::rx::Observable<void> SYSTEM_SERVICE_OUT_observable = sc::rx::Observable<void>{};
		
		/*! Indicates event 'ESTOP_1_HIGH' of default interface scope is active. */
		bool ESTOP_1_HIGH_raised {false};
		
		/*! Indicates event 'ESTOP_1_LOW' of default interface scope is active. */
		bool ESTOP_1_LOW_raised {false};
		
		/*! Observable for event 'ESTOP_RECEIVED' of default interface scope. */
		sc::rx::Observable<void> ESTOP_RECEIVED_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'ESTOP_CLEARED' of default interface scope. */
		sc::rx::Observable<void> ESTOP_CLEARED_observable = sc::rx::Observable<void>{};
		
		/*! Indicates event 'LBF_1_INTERRUPTED' of default interface scope is active. */
		bool LBF_1_INTERRUPTED_raised {false};
		
		/*! Indicates event 'LBF_1_OPEN' of default interface scope is active. */
		bool LBF_1_OPEN_raised {false};
		
		/*! Indicates event 'PUK_ENTRY_HeightMeasurement' of default interface scope is active. */
		bool PUK_ENTRY_HeightMeasurement_raised {false};
		
		/*! Indicates event 'INGRESS_IN' of default interface scope is active. */
		bool INGRESS_IN_raised {false};
		
		/*! Indicates event 'INGRESS_OUT' of default interface scope is active. */
		bool INGRESS_OUT_raised {false};
		
		/*! Indicates event 'HS_1_SAMPLE' of default interface scope is active. */
		bool HS_1_SAMPLE_raised {false};
		
		/*! Indicates event 'HS_1_SAMPLING_DONE' of default interface scope is active. */
		bool HS_1_SAMPLING_DONE_raised {false};
		
		/*! Observable for event 'PUK_DISTANCE_VALID' of default interface scope. */
		sc::rx::Observable<void> PUK_DISTANCE_VALID_observable = sc::rx::Observable<void>{};
		
		/*! Indicates event 'PUK_ENTRY_SORTING' of default interface scope is active. */
		bool PUK_ENTRY_SORTING_raised {false};
		
		/*! Indicates event 'TIMEOUT_200' of default interface scope is active. */
		bool TIMEOUT_200_raised {false};
		
		/*! Indicates event 'LBM_1_INTERRUPTED' of default interface scope is active. */
		bool LBM_1_INTERRUPTED_raised {false};
		
		/*! Indicates event 'LBM_1_OPEN' of default interface scope is active. */
		bool LBM_1_OPEN_raised {false};
		
		/*! Indicates event 'MS_TRUE' of default interface scope is active. */
		bool MS_TRUE_raised {false};
		
		/*! Indicates event 'MS_FALSE' of default interface scope is active. */
		bool MS_FALSE_raised {false};
		
		/*! Indicates event 'PUK_DESIRED' of default interface scope is active. */
		bool PUK_DESIRED_raised {false};
		
		/*! Indicates event 'PUK_NOT_DESIRED' of default interface scope is active. */
		bool PUK_NOT_DESIRED_raised {false};
		
		/*! Observable for event 'PUK_ENTRY_EGRESS' of default interface scope. */
		sc::rx::Observable<void> PUK_ENTRY_EGRESS_observable = sc::rx::Observable<void>{};
		
		/*! Indicates event 'PUK_EJECTOR_DISTANCE_VALID' of default interface scope is active. */
		bool PUK_EJECTOR_DISTANCE_VALID_raised {false};
		
		/*! Indicates event 'LBR_1_INTERRUPTED' of default interface scope is active. */
		bool LBR_1_INTERRUPTED_raised {false};
		
		/*! Indicates event 'LBR_1_OPEN' of default interface scope is active. */
		bool LBR_1_OPEN_raised {false};
		
		/*! Observable for event 'SORTING_MODULE_ACTIVE' of default interface scope. */
		sc::rx::Observable<void> SORTING_MODULE_ACTIVE_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'SORTING_MODULE_RESTING' of default interface scope. */
		sc::rx::Observable<void> SORTING_MODULE_RESTING_observable = sc::rx::Observable<void>{};
		
		/*! Indicates event 'LBE_1_OPEN' of default interface scope is active. */
		bool LBE_1_OPEN_raised {false};
		
		/*! Indicates event 'LBE_1_INTERRUPTED' of default interface scope is active. */
		bool LBE_1_INTERRUPTED_raised {false};
		
		/*! Observable for event 'MOTOR_STOP' of default interface scope. */
		sc::rx::Observable<void> MOTOR_STOP_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'MOTOR_FAST' of default interface scope. */
		sc::rx::Observable<void> MOTOR_FAST_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'MOTOR_SLOW' of default interface scope. */
		sc::rx::Observable<void> MOTOR_SLOW_observable = sc::rx::Observable<void>{};
		
		/*! Indicates event 'BGS_1_LONG_PRESSED' of default interface scope is active. */
		bool BGS_1_LONG_PRESSED_raised {false};
		
		/*! Indicates event 'BGS_1_INTERRUPTED' of default interface scope is active. */
		bool BGS_1_INTERRUPTED_raised {false};
		
		/*! Indicates event 'BRS_1_INTERRUPTED' of default interface scope is active. */
		bool BRS_1_INTERRUPTED_raised {false};
		
		/*! Indicates event 'BGR_1_INTERRUPTED' of default interface scope is active. */
		bool BGR_1_INTERRUPTED_raised {false};
		
		/*! Indicates event 'LampEStop' of default interface scope is active. */
		bool LampEStop_raised {false};
		
		/*! Indicates event 'Lamp' of default interface scope is active. */
		bool Lamp_raised {false};
		
		/*! Observable for event 'LG1_ON' of default interface scope. */
		sc::rx::Observable<void> LG1_ON_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'LG1_BLINKING_1HZ' of default interface scope. */
		sc::rx::Observable<void> LG1_BLINKING_1HZ_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'LG1_OFF' of default interface scope. */
		sc::rx::Observable<void> LG1_OFF_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'LY1_ON' of default interface scope. */
		sc::rx::Observable<void> LY1_ON_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'LY1_BLINKING_1HZ' of default interface scope. */
		sc::rx::Observable<void> LY1_BLINKING_1HZ_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'LY1_OFF' of default interface scope. */
		sc::rx::Observable<void> LY1_OFF_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'LR1_ON' of default interface scope. */
		sc::rx::Observable<void> LR1_ON_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'LR1_OFF' of default interface scope. */
		sc::rx::Observable<void> LR1_OFF_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'SYSTEM_RUNNING' of default interface scope. */
		sc::rx::Observable<void> SYSTEM_RUNNING_observable = sc::rx::Observable<void>{};
		
		/*! Observable for event 'SYSTEM_STOPPED' of default interface scope. */
		sc::rx::Observable<void> SYSTEM_STOPPED_observable = sc::rx::Observable<void>{};
		
		/*! Indicates event 'ESTOP_SIGNAL' of default interface scope is active. */
		bool ESTOP_SIGNAL_raised {false};
		
		/*! Indicates event 'ESTOP_SIGNAL_RESET' of default interface scope is active. */
		bool ESTOP_SIGNAL_RESET_raised {false};
		
		/*! Indicates event 'RUNNING_SIGNAL' of default interface scope is active. */
		bool RUNNING_SIGNAL_raised {false};
		
		/*! Indicates event 'RUNNING_SIGNAL_RESET' of default interface scope is active. */
		bool RUNNING_SIGNAL_RESET_raised {false};
		
		/*! Indicates event 'WARNING_SIGNAL' of default interface scope is active. */
		bool WARNING_SIGNAL_raised {false};
		
		/*! Indicates event 'WARNING_SIGNAL_RESET' of default interface scope is active. */
		bool WARNING_SIGNAL_RESET_raised {false};
		
		/*! Indicates event 'READY_SIGNAL' of default interface scope is active. */
		bool READY_SIGNAL_raised {false};
		
		/*! Indicates event 'READY_RESET' of default interface scope is active. */
		bool READY_RESET_raised {false};
		
		/*! Indicates event 'ERROR_SIGNAL' of default interface scope is active. */
		bool ERROR_SIGNAL_raised {false};
		
		/*! Indicates event 'local_SYSTEM_OPERATIONAL_OUT' of internal scope is active. */
		bool local_SYSTEM_OPERATIONAL_OUT_raised {false};
		
		/*! Raises the out event 'local_SYSTEM_OPERATIONAL_OUT' of internal scope as a local event. */
		void raiseLocal_SYSTEM_OPERATIONAL_OUT();
		
		/*! Indicates event 'local_PUK_DISTANCE_VALID' of internal scope is active. */
		bool local_PUK_DISTANCE_VALID_raised {false};
		
		/*! Raises the out event 'local_PUK_DISTANCE_VALID' of internal scope as a local event. */
		void raiseLocal_PUK_DISTANCE_VALID();
		
		/*! Indicates event 'local_SYSTEM_OPERATIONAL_IN' of internal scope is active. */
		bool local_SYSTEM_OPERATIONAL_IN_raised {false};
		
		/*! Raises the out event 'local_SYSTEM_OPERATIONAL_IN' of internal scope as a local event. */
		void raiseLocal_SYSTEM_OPERATIONAL_IN();
		
		/*! Indicates event 'local_PUK_ENTRY_EGRESS' of internal scope is active. */
		bool local_PUK_ENTRY_EGRESS_raised {false};
		
		/*! Raises the out event 'local_PUK_ENTRY_EGRESS' of internal scope as a local event. */
		void raiseLocal_PUK_ENTRY_EGRESS();
		
		/*! Indicates event 'local_ESTOP_RECEIVED' of internal scope is active. */
		bool local_ESTOP_RECEIVED_raised {false};
		
		/*! Raises the out event 'local_ESTOP_RECEIVED' of internal scope as a local event. */
		void raiseLocal_ESTOP_RECEIVED();
		
		/*! Indicates event 'local_SYSTEM_SERVICE_IN' of internal scope is active. */
		bool local_SYSTEM_SERVICE_IN_raised {false};
		
		/*! Raises the out event 'local_SYSTEM_SERVICE_IN' of internal scope as a local event. */
		void raiseLocal_SYSTEM_SERVICE_IN();
		
		/*! Indicates event 'local_ESTOP_CLEARED' of internal scope is active. */
		bool local_ESTOP_CLEARED_raised {false};
		
		/*! Raises the out event 'local_ESTOP_CLEARED' of internal scope as a local event. */
		void raiseLocal_ESTOP_CLEARED();
		
		/*! Indicates event 'local_SYSTEM_SERVICE_OUT' of internal scope is active. */
		bool local_SYSTEM_SERVICE_OUT_raised {false};
		
		/*! Raises the out event 'local_SYSTEM_SERVICE_OUT' of internal scope as a local event. */
		void raiseLocal_SYSTEM_SERVICE_OUT();
		
		
		
};




#endif /* FSM_QUALITYGATE_H_ */
