/*
 * PulseMsgConfig.h
 *
 *  Created on: 04.12.2024
 *      Author: Marc
 */

#ifndef DISPATCHER_PULSEMSGCONFIG_H_
#define DISPATCHER_PULSEMSGCONFIG_H_

// typedef struct PulseEventMsg {
//     int32_t type;
//     int32_t coid;
//     void *payload;
// } PulseEventMsg_t;

// TODO IMPLEMENT WITH ENUM TO MAKE CODES EASIER TO MAINTAIN

// PulseCodes GENERAL
#define PULSE_STOP_THREAD _PULSE_CODE_MINAVAIL + 1

// PULSECODE DECODER
#define PULSE_INTR_ON_PORT0 _PULSE_CODE_MINAVAIL + 2

// Pulse Codes HEARTBEAT
#define PULSE_HEARTBEAT _PULSE_CODE_MINAVAIL + 3

// PULSECODES SENSORS
#define PULSE_INTR_ON_ESTOP _PULSE_CODE_MINAVAIL + 4
#define PULSE_LBF1_INTERRUPTED _PULSE_CODE_MINAVAIL + 9
#define PULSE_LBF1_OPEN _PULSE_CODE_MINAVAIL + 10
// #define PULSE_INTR_ON_ESTOP _PULSE_CODE_MINAVAIL + 5
// #define PULSE_INTR_ON_ESTOP _PULSE_CODE_MINAVAIL + 6
// #define PULSE_INTR_ON_ESTOP _PULSE_CODE_MINAVAIL + 7
// #define PULSE_INTR_ON_ESTOP _PULSE_CODE_MINAVAIL + 8
// #define PULSE_INTR_ON_ESTOP _PULSE_CODE_MINAVAIL + 9

// PULSECODES ACTUATOR CONTROLLER
#define PULSE_MOTOR_STOP _PULSE_CODE_MINAVAIL + 5
#define PULSE_MOTOR_START _PULSE_CODE_MINAVAIL + 6
#define PULSE_MOTOR_SLOW _PULSE_CODE_MINAVAIL + 7
#define PULSE_MOTOR_FAST _PULSE_CODE_MINAVAIL + 8

#endif /* DISPATCHER_PULSEMSGCONFIG_H_ */
